#+TITLE: A Python parser for Org Mode documents
#+ARCHIVE: ./docs/plans/ROADMAP_ARCHIVE.org::

* Bugfixes
** DONE Bump tree-sitter-org to 0.23.7
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-05 Sun 17:51]
:END:

** TODO =ListItem= representation omits the counter

* Additions
** TODO =RichText.trimmed=
Add a new read-only attribute to the =RichText= class that returns a new =RichText= object that has any leading or trailing whitespace removed.

** TODO =RichText.stripped=
Add a new read-only attribute to the =RichText= class that returns a new =RichText= object that has inline markup stripped according to the following rules:
- Bold, italic, underline etc markup is replaced with the raw body without the markup. Take special care for nested markup.
- Links, cites and footnotes with a description are replaced with the description.
- Links, cites and footnotes without a description are replaced with the link value (without the brackets).
- All other inline objects including Timestamps are replaced with their textual representation.

The goal is for the =stripped= attribute to be a visual representation of a string of =RichText= without the markup. Essentially, =stripped= rich text will consist mostly of plaintext objects.

** TODO =to_json()= convenience method
All objects should be convertible to "simple" JSON objects:
- =RichText= should be represented by its string representation value,
- All other objects should become JSON objects with a =type= field indicating the class-name of the underlying object and an attribute for each of the writable attributes of the object.

Omit the =children=, =siblings=, =parent=, =all_heading= and any other fields that could lead to a recursive conversion.
Prefer =body= and =title= to =body_text= and =title_text=, etc.

** TODO =Properties= to accept any type of property value
Automatically stringify these for dirty rendering.

** TODO =Repeat.is_complete= convenience attribute
